### ISSUE TITLE
DMArchiver stopped working: "Unknown element type"

### ISSUE THREAD

**Issue by Gorrrg** [Mincka/DMArchiver#14]
Since just a few days downloading the direct messages doesn't work anymore. Something in the HTML mus thave changed on Twitter's side.

I get the error `Unknown element type`. In the txt file the date, time and username is there but the actual text message is missing.

**Comment by Gorrrg** [comment]
Ok, I found the issue. They added another layer in the HTML code. Another DIV class. `dm_elements` should not be taken from `DirectMessage-message` but one level below from `DirectMessage-contentContainer`.

Changing that in line 463 made the script work again.

```
                    dm_elements = document.cssselect(
                        'div.DirectMessage-contentContainer > div[class^="DirectMessage-"], div.DirectMessage-message > div[class*=" DirectMessage-"]')
```

**Comment by Mincka** [comment]
Thanks a lot for the reporting and the fix! I hope to be able to release new versions for all the platforms this week.

**Comment by Mincka** [comment]
The proposed fix worked perfectly. Thanks a lot.
Fixed in https://github.com/Mincka/DMArchiver/commit/21eecee22d1e22f2e544f39cd30a184e23cd1dcc

**Comment by goofyhsk** [comment]
-di and -dg aren't grabbing anything with this latest release (win x86-64)

**Comment by Gorrrg** [comment]
Yes, my fix worked only for text messages.
https://github.com/Mincka/DMArchiver/issues/16

**Comment by sussron** [comment]
Hi Julien,
I've downloaded the most recent release as I hadn't backed up messages since February.  I decided to do just one of the conversations  with images. I i put in the commands as you showed me (remember I'm not the techie one here so i apologize for my ignorance) . i'm still getting the Unknown element error that other users mentioned in prior threads.  it is still processing tweets, but what is it not including so that I'm sure what i'm getting?  Thanks in advance for your help

Thanks,
Ronnie
<img width="631" alt="screenshot 2017-06-24 18 19 22" src="https://user-images.githubusercontent.com/22826606/27512302-2b3050bc-590a-11e7-968c-2dfeef6cad4c.png">

@beckybulldognj
